// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_DC_DM_REGISTER.proto

#ifndef PROTOBUF_MSG_5fDC_5fDM_5fREGISTER_2eproto__INCLUDED
#define PROTOBUF_MSG_5fDC_5fDM_5fREGISTER_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MSG_5fDC_5fDM_5fREGISTER_2eproto();
void protobuf_AssignDesc_MSG_5fDC_5fDM_5fREGISTER_2eproto();
void protobuf_ShutdownFile_MSG_5fDC_5fDM_5fREGISTER_2eproto();

class MSG_DC_DM_REGISTER;
class MSG_DM_DC_REGISTER_ACK;

// ===================================================================

class MSG_DC_DM_REGISTER : public ::google::protobuf::Message {
 public:
  MSG_DC_DM_REGISTER();
  virtual ~MSG_DC_DM_REGISTER();
  
  MSG_DC_DM_REGISTER(const MSG_DC_DM_REGISTER& from);
  
  inline MSG_DC_DM_REGISTER& operator=(const MSG_DC_DM_REGISTER& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DC_DM_REGISTER& default_instance();
  
  void Swap(MSG_DC_DM_REGISTER* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DC_DM_REGISTER* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DC_DM_REGISTER& from);
  void MergeFrom(const MSG_DC_DM_REGISTER& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 moduleID = 1;
  inline bool has_moduleid() const;
  inline void clear_moduleid();
  static const int kModuleIDFieldNumber = 1;
  inline ::google::protobuf::uint32 moduleid() const;
  inline void set_moduleid(::google::protobuf::uint32 value);
  
  // optional string IP = 2;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIPFieldNumber = 2;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const char* value, size_t size);
  inline ::std::string* mutable_ip();
  inline ::std::string* release_ip();
  
  // optional uint32 port = 3;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 3;
  inline ::google::protobuf::uint32 port() const;
  inline void set_port(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:MSG_DC_DM_REGISTER)
 private:
  inline void set_has_moduleid();
  inline void clear_has_moduleid();
  inline void set_has_ip();
  inline void clear_has_ip();
  inline void set_has_port();
  inline void clear_has_port();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ip_;
  ::google::protobuf::uint32 moduleid_;
  ::google::protobuf::uint32 port_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fDC_5fDM_5fREGISTER_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDC_5fDM_5fREGISTER_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDC_5fDM_5fREGISTER_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DC_DM_REGISTER* default_instance_;
};
// -------------------------------------------------------------------

class MSG_DM_DC_REGISTER_ACK : public ::google::protobuf::Message {
 public:
  MSG_DM_DC_REGISTER_ACK();
  virtual ~MSG_DM_DC_REGISTER_ACK();
  
  MSG_DM_DC_REGISTER_ACK(const MSG_DM_DC_REGISTER_ACK& from);
  
  inline MSG_DM_DC_REGISTER_ACK& operator=(const MSG_DM_DC_REGISTER_ACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DM_DC_REGISTER_ACK& default_instance();
  
  void Swap(MSG_DM_DC_REGISTER_ACK* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DM_DC_REGISTER_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DM_DC_REGISTER_ACK& from);
  void MergeFrom(const MSG_DM_DC_REGISTER_ACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 statusCode = 1;
  inline bool has_statuscode() const;
  inline void clear_statuscode();
  static const int kStatusCodeFieldNumber = 1;
  inline ::google::protobuf::int32 statuscode() const;
  inline void set_statuscode(::google::protobuf::int32 value);
  
  // optional string domainName = 2;
  inline bool has_domainname() const;
  inline void clear_domainname();
  static const int kDomainNameFieldNumber = 2;
  inline const ::std::string& domainname() const;
  inline void set_domainname(const ::std::string& value);
  inline void set_domainname(const char* value);
  inline void set_domainname(const char* value, size_t size);
  inline ::std::string* mutable_domainname();
  inline ::std::string* release_domainname();
  
  // @@protoc_insertion_point(class_scope:MSG_DM_DC_REGISTER_ACK)
 private:
  inline void set_has_statuscode();
  inline void clear_has_statuscode();
  inline void set_has_domainname();
  inline void clear_has_domainname();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* domainname_;
  ::google::protobuf::int32 statuscode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fDC_5fDM_5fREGISTER_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDC_5fDM_5fREGISTER_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDC_5fDM_5fREGISTER_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DM_DC_REGISTER_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_DC_DM_REGISTER

// optional uint32 moduleID = 1;
inline bool MSG_DC_DM_REGISTER::has_moduleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DC_DM_REGISTER::set_has_moduleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DC_DM_REGISTER::clear_has_moduleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DC_DM_REGISTER::clear_moduleid() {
  moduleid_ = 0u;
  clear_has_moduleid();
}
inline ::google::protobuf::uint32 MSG_DC_DM_REGISTER::moduleid() const {
  return moduleid_;
}
inline void MSG_DC_DM_REGISTER::set_moduleid(::google::protobuf::uint32 value) {
  set_has_moduleid();
  moduleid_ = value;
}

// optional string IP = 2;
inline bool MSG_DC_DM_REGISTER::has_ip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_DC_DM_REGISTER::set_has_ip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_DC_DM_REGISTER::clear_has_ip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_DC_DM_REGISTER::clear_ip() {
  if (ip_ != &::google::protobuf::internal::kEmptyString) {
    ip_->clear();
  }
  clear_has_ip();
}
inline const ::std::string& MSG_DC_DM_REGISTER::ip() const {
  return *ip_;
}
inline void MSG_DC_DM_REGISTER::set_ip(const ::std::string& value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
}
inline void MSG_DC_DM_REGISTER::set_ip(const char* value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
}
inline void MSG_DC_DM_REGISTER::set_ip(const char* value, size_t size) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  ip_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_DC_DM_REGISTER::mutable_ip() {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  return ip_;
}
inline ::std::string* MSG_DC_DM_REGISTER::release_ip() {
  clear_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ip_;
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional uint32 port = 3;
inline bool MSG_DC_DM_REGISTER::has_port() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MSG_DC_DM_REGISTER::set_has_port() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MSG_DC_DM_REGISTER::clear_has_port() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MSG_DC_DM_REGISTER::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 MSG_DC_DM_REGISTER::port() const {
  return port_;
}
inline void MSG_DC_DM_REGISTER::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
}

// -------------------------------------------------------------------

// MSG_DM_DC_REGISTER_ACK

// optional int32 statusCode = 1;
inline bool MSG_DM_DC_REGISTER_ACK::has_statuscode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DM_DC_REGISTER_ACK::set_has_statuscode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DM_DC_REGISTER_ACK::clear_has_statuscode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DM_DC_REGISTER_ACK::clear_statuscode() {
  statuscode_ = 0;
  clear_has_statuscode();
}
inline ::google::protobuf::int32 MSG_DM_DC_REGISTER_ACK::statuscode() const {
  return statuscode_;
}
inline void MSG_DM_DC_REGISTER_ACK::set_statuscode(::google::protobuf::int32 value) {
  set_has_statuscode();
  statuscode_ = value;
}

// optional string domainName = 2;
inline bool MSG_DM_DC_REGISTER_ACK::has_domainname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_DM_DC_REGISTER_ACK::set_has_domainname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_DM_DC_REGISTER_ACK::clear_has_domainname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_DM_DC_REGISTER_ACK::clear_domainname() {
  if (domainname_ != &::google::protobuf::internal::kEmptyString) {
    domainname_->clear();
  }
  clear_has_domainname();
}
inline const ::std::string& MSG_DM_DC_REGISTER_ACK::domainname() const {
  return *domainname_;
}
inline void MSG_DM_DC_REGISTER_ACK::set_domainname(const ::std::string& value) {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  domainname_->assign(value);
}
inline void MSG_DM_DC_REGISTER_ACK::set_domainname(const char* value) {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  domainname_->assign(value);
}
inline void MSG_DM_DC_REGISTER_ACK::set_domainname(const char* value, size_t size) {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  domainname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_DM_DC_REGISTER_ACK::mutable_domainname() {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  return domainname_;
}
inline ::std::string* MSG_DM_DC_REGISTER_ACK::release_domainname() {
  clear_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = domainname_;
    domainname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fDC_5fDM_5fREGISTER_2eproto__INCLUDED
