// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_DC_DM_CONFIG_LOOKUP.proto

#ifndef PROTOBUF_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto__INCLUDED
#define PROTOBUF_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
void protobuf_AssignDesc_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
void protobuf_ShutdownFile_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();

class MSG_DC_DM_CONFIG_LOOKUP;
class MSG_DM_DC_CONFIG_LOOKUP_ACK;

// ===================================================================

class MSG_DC_DM_CONFIG_LOOKUP : public ::google::protobuf::Message {
 public:
  MSG_DC_DM_CONFIG_LOOKUP();
  virtual ~MSG_DC_DM_CONFIG_LOOKUP();
  
  MSG_DC_DM_CONFIG_LOOKUP(const MSG_DC_DM_CONFIG_LOOKUP& from);
  
  inline MSG_DC_DM_CONFIG_LOOKUP& operator=(const MSG_DC_DM_CONFIG_LOOKUP& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DC_DM_CONFIG_LOOKUP& default_instance();
  
  void Swap(MSG_DC_DM_CONFIG_LOOKUP* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DC_DM_CONFIG_LOOKUP* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DC_DM_CONFIG_LOOKUP& from);
  void MergeFrom(const MSG_DC_DM_CONFIG_LOOKUP& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string domainName = 1;
  inline bool has_domainname() const;
  inline void clear_domainname();
  static const int kDomainNameFieldNumber = 1;
  inline const ::std::string& domainname() const;
  inline void set_domainname(const ::std::string& value);
  inline void set_domainname(const char* value);
  inline void set_domainname(const char* value, size_t size);
  inline ::std::string* mutable_domainname();
  inline ::std::string* release_domainname();
  
  // @@protoc_insertion_point(class_scope:MSG_DC_DM_CONFIG_LOOKUP)
 private:
  inline void set_has_domainname();
  inline void clear_has_domainname();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* domainname_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DC_DM_CONFIG_LOOKUP* default_instance_;
};
// -------------------------------------------------------------------

class MSG_DM_DC_CONFIG_LOOKUP_ACK : public ::google::protobuf::Message {
 public:
  MSG_DM_DC_CONFIG_LOOKUP_ACK();
  virtual ~MSG_DM_DC_CONFIG_LOOKUP_ACK();
  
  MSG_DM_DC_CONFIG_LOOKUP_ACK(const MSG_DM_DC_CONFIG_LOOKUP_ACK& from);
  
  inline MSG_DM_DC_CONFIG_LOOKUP_ACK& operator=(const MSG_DM_DC_CONFIG_LOOKUP_ACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DM_DC_CONFIG_LOOKUP_ACK& default_instance();
  
  void Swap(MSG_DM_DC_CONFIG_LOOKUP_ACK* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DM_DC_CONFIG_LOOKUP_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DM_DC_CONFIG_LOOKUP_ACK& from);
  void MergeFrom(const MSG_DM_DC_CONFIG_LOOKUP_ACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 statusCode = 1;
  inline bool has_statuscode() const;
  inline void clear_statuscode();
  static const int kStatusCodeFieldNumber = 1;
  inline ::google::protobuf::int32 statuscode() const;
  inline void set_statuscode(::google::protobuf::int32 value);
  
  // repeated string raIp = 2;
  inline int raip_size() const;
  inline void clear_raip();
  static const int kRaIpFieldNumber = 2;
  inline const ::std::string& raip(int index) const;
  inline ::std::string* mutable_raip(int index);
  inline void set_raip(int index, const ::std::string& value);
  inline void set_raip(int index, const char* value);
  inline void set_raip(int index, const char* value, size_t size);
  inline ::std::string* add_raip();
  inline void add_raip(const ::std::string& value);
  inline void add_raip(const char* value);
  inline void add_raip(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& raip() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_raip();
  
  // @@protoc_insertion_point(class_scope:MSG_DM_DC_CONFIG_LOOKUP_ACK)
 private:
  inline void set_has_statuscode();
  inline void clear_has_statuscode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> raip_;
  ::google::protobuf::int32 statuscode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
  friend void protobuf_AssignDesc_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DM_DC_CONFIG_LOOKUP_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_DC_DM_CONFIG_LOOKUP

// optional string domainName = 1;
inline bool MSG_DC_DM_CONFIG_LOOKUP::has_domainname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DC_DM_CONFIG_LOOKUP::set_has_domainname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DC_DM_CONFIG_LOOKUP::clear_has_domainname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DC_DM_CONFIG_LOOKUP::clear_domainname() {
  if (domainname_ != &::google::protobuf::internal::kEmptyString) {
    domainname_->clear();
  }
  clear_has_domainname();
}
inline const ::std::string& MSG_DC_DM_CONFIG_LOOKUP::domainname() const {
  return *domainname_;
}
inline void MSG_DC_DM_CONFIG_LOOKUP::set_domainname(const ::std::string& value) {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  domainname_->assign(value);
}
inline void MSG_DC_DM_CONFIG_LOOKUP::set_domainname(const char* value) {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  domainname_->assign(value);
}
inline void MSG_DC_DM_CONFIG_LOOKUP::set_domainname(const char* value, size_t size) {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  domainname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_DC_DM_CONFIG_LOOKUP::mutable_domainname() {
  set_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    domainname_ = new ::std::string;
  }
  return domainname_;
}
inline ::std::string* MSG_DC_DM_CONFIG_LOOKUP::release_domainname() {
  clear_has_domainname();
  if (domainname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = domainname_;
    domainname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// MSG_DM_DC_CONFIG_LOOKUP_ACK

// optional int32 statusCode = 1;
inline bool MSG_DM_DC_CONFIG_LOOKUP_ACK::has_statuscode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::set_has_statuscode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::clear_has_statuscode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::clear_statuscode() {
  statuscode_ = 0;
  clear_has_statuscode();
}
inline ::google::protobuf::int32 MSG_DM_DC_CONFIG_LOOKUP_ACK::statuscode() const {
  return statuscode_;
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::set_statuscode(::google::protobuf::int32 value) {
  set_has_statuscode();
  statuscode_ = value;
}

// repeated string raIp = 2;
inline int MSG_DM_DC_CONFIG_LOOKUP_ACK::raip_size() const {
  return raip_.size();
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::clear_raip() {
  raip_.Clear();
}
inline const ::std::string& MSG_DM_DC_CONFIG_LOOKUP_ACK::raip(int index) const {
  return raip_.Get(index);
}
inline ::std::string* MSG_DM_DC_CONFIG_LOOKUP_ACK::mutable_raip(int index) {
  return raip_.Mutable(index);
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::set_raip(int index, const ::std::string& value) {
  raip_.Mutable(index)->assign(value);
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::set_raip(int index, const char* value) {
  raip_.Mutable(index)->assign(value);
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::set_raip(int index, const char* value, size_t size) {
  raip_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_DM_DC_CONFIG_LOOKUP_ACK::add_raip() {
  return raip_.Add();
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::add_raip(const ::std::string& value) {
  raip_.Add()->assign(value);
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::add_raip(const char* value) {
  raip_.Add()->assign(value);
}
inline void MSG_DM_DC_CONFIG_LOOKUP_ACK::add_raip(const char* value, size_t size) {
  raip_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MSG_DM_DC_CONFIG_LOOKUP_ACK::raip() const {
  return raip_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MSG_DM_DC_CONFIG_LOOKUP_ACK::mutable_raip() {
  return &raip_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fDC_5fDM_5fCONFIG_5fLOOKUP_2eproto__INCLUDED
