// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_CLIENT_DM_GROUP_DESTROY.proto

#ifndef PROTOBUF_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto__INCLUDED
#define PROTOBUF_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
void protobuf_AssignDesc_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
void protobuf_ShutdownFile_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();

class MSG_CLIENT_DM_GROUP_DESTROY;
class MSG_DM_CLIENT_GROUP_DESTROY_ACK;

// ===================================================================

class MSG_CLIENT_DM_GROUP_DESTROY : public ::google::protobuf::Message {
 public:
  MSG_CLIENT_DM_GROUP_DESTROY();
  virtual ~MSG_CLIENT_DM_GROUP_DESTROY();
  
  MSG_CLIENT_DM_GROUP_DESTROY(const MSG_CLIENT_DM_GROUP_DESTROY& from);
  
  inline MSG_CLIENT_DM_GROUP_DESTROY& operator=(const MSG_CLIENT_DM_GROUP_DESTROY& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_CLIENT_DM_GROUP_DESTROY& default_instance();
  
  void Swap(MSG_CLIENT_DM_GROUP_DESTROY* other);
  
  // implements Message ----------------------------------------------
  
  MSG_CLIENT_DM_GROUP_DESTROY* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_CLIENT_DM_GROUP_DESTROY& from);
  void MergeFrom(const MSG_CLIENT_DM_GROUP_DESTROY& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string token = 1;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 1;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  
  // optional string groupName = 2;
  inline bool has_groupname() const;
  inline void clear_groupname();
  static const int kGroupNameFieldNumber = 2;
  inline const ::std::string& groupname() const;
  inline void set_groupname(const ::std::string& value);
  inline void set_groupname(const char* value);
  inline void set_groupname(const char* value, size_t size);
  inline ::std::string* mutable_groupname();
  inline ::std::string* release_groupname();
  
  // @@protoc_insertion_point(class_scope:MSG_CLIENT_DM_GROUP_DESTROY)
 private:
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_groupname();
  inline void clear_has_groupname();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* token_;
  ::std::string* groupname_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
  friend void protobuf_AssignDesc_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_CLIENT_DM_GROUP_DESTROY* default_instance_;
};
// -------------------------------------------------------------------

class MSG_DM_CLIENT_GROUP_DESTROY_ACK : public ::google::protobuf::Message {
 public:
  MSG_DM_CLIENT_GROUP_DESTROY_ACK();
  virtual ~MSG_DM_CLIENT_GROUP_DESTROY_ACK();
  
  MSG_DM_CLIENT_GROUP_DESTROY_ACK(const MSG_DM_CLIENT_GROUP_DESTROY_ACK& from);
  
  inline MSG_DM_CLIENT_GROUP_DESTROY_ACK& operator=(const MSG_DM_CLIENT_GROUP_DESTROY_ACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_DM_CLIENT_GROUP_DESTROY_ACK& default_instance();
  
  void Swap(MSG_DM_CLIENT_GROUP_DESTROY_ACK* other);
  
  // implements Message ----------------------------------------------
  
  MSG_DM_CLIENT_GROUP_DESTROY_ACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_DM_CLIENT_GROUP_DESTROY_ACK& from);
  void MergeFrom(const MSG_DM_CLIENT_GROUP_DESTROY_ACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 statusCode = 1;
  inline bool has_statuscode() const;
  inline void clear_statuscode();
  static const int kStatusCodeFieldNumber = 1;
  inline ::google::protobuf::int32 statuscode() const;
  inline void set_statuscode(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MSG_DM_CLIENT_GROUP_DESTROY_ACK)
 private:
  inline void set_has_statuscode();
  inline void clear_has_statuscode();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 statuscode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
  friend void protobuf_AssignDesc_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
  friend void protobuf_ShutdownFile_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto();
  
  void InitAsDefaultInstance();
  static MSG_DM_CLIENT_GROUP_DESTROY_ACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MSG_CLIENT_DM_GROUP_DESTROY

// optional string token = 1;
inline bool MSG_CLIENT_DM_GROUP_DESTROY::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::clear_token() {
  if (token_ != &::google::protobuf::internal::kEmptyString) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MSG_CLIENT_DM_GROUP_DESTROY::token() const {
  return *token_;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  token_->assign(value);
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  token_->assign(value);
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_CLIENT_DM_GROUP_DESTROY::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    token_ = new ::std::string;
  }
  return token_;
}
inline ::std::string* MSG_CLIENT_DM_GROUP_DESTROY::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string groupName = 2;
inline bool MSG_CLIENT_DM_GROUP_DESTROY::has_groupname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_has_groupname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::clear_has_groupname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::clear_groupname() {
  if (groupname_ != &::google::protobuf::internal::kEmptyString) {
    groupname_->clear();
  }
  clear_has_groupname();
}
inline const ::std::string& MSG_CLIENT_DM_GROUP_DESTROY::groupname() const {
  return *groupname_;
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_groupname(const ::std::string& value) {
  set_has_groupname();
  if (groupname_ == &::google::protobuf::internal::kEmptyString) {
    groupname_ = new ::std::string;
  }
  groupname_->assign(value);
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_groupname(const char* value) {
  set_has_groupname();
  if (groupname_ == &::google::protobuf::internal::kEmptyString) {
    groupname_ = new ::std::string;
  }
  groupname_->assign(value);
}
inline void MSG_CLIENT_DM_GROUP_DESTROY::set_groupname(const char* value, size_t size) {
  set_has_groupname();
  if (groupname_ == &::google::protobuf::internal::kEmptyString) {
    groupname_ = new ::std::string;
  }
  groupname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MSG_CLIENT_DM_GROUP_DESTROY::mutable_groupname() {
  set_has_groupname();
  if (groupname_ == &::google::protobuf::internal::kEmptyString) {
    groupname_ = new ::std::string;
  }
  return groupname_;
}
inline ::std::string* MSG_CLIENT_DM_GROUP_DESTROY::release_groupname() {
  clear_has_groupname();
  if (groupname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = groupname_;
    groupname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// MSG_DM_CLIENT_GROUP_DESTROY_ACK

// optional int32 statusCode = 1;
inline bool MSG_DM_CLIENT_GROUP_DESTROY_ACK::has_statuscode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSG_DM_CLIENT_GROUP_DESTROY_ACK::set_has_statuscode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSG_DM_CLIENT_GROUP_DESTROY_ACK::clear_has_statuscode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSG_DM_CLIENT_GROUP_DESTROY_ACK::clear_statuscode() {
  statuscode_ = 0;
  clear_has_statuscode();
}
inline ::google::protobuf::int32 MSG_DM_CLIENT_GROUP_DESTROY_ACK::statuscode() const {
  return statuscode_;
}
inline void MSG_DM_CLIENT_GROUP_DESTROY_ACK::set_statuscode(::google::protobuf::int32 value) {
  set_has_statuscode();
  statuscode_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fCLIENT_5fDM_5fGROUP_5fDESTROY_2eproto__INCLUDED
