// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MSG_CLIENT_DM_DOMAIN_CREATE.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MSG_CLIENT_DM_DOMAIN_CREATE_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_CLIENT_DM_DOMAIN_CREATE_reflection_ = NULL;
const ::google::protobuf::Descriptor* MSG_DM_CLIENT_DOMAIN_CREATE_ACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_DM_CLIENT_DOMAIN_CREATE_ACK_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto() {
  protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MSG_CLIENT_DM_DOMAIN_CREATE.proto");
  GOOGLE_CHECK(file != NULL);
  MSG_CLIENT_DM_DOMAIN_CREATE_descriptor_ = file->message_type(0);
  static const int MSG_CLIENT_DM_DOMAIN_CREATE_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, token_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, domainname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, domaindescription_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, corenum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, memsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, filepath_),
  };
  MSG_CLIENT_DM_DOMAIN_CREATE_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_CLIENT_DM_DOMAIN_CREATE_descriptor_,
      MSG_CLIENT_DM_DOMAIN_CREATE::default_instance_,
      MSG_CLIENT_DM_DOMAIN_CREATE_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_CLIENT_DM_DOMAIN_CREATE, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_CLIENT_DM_DOMAIN_CREATE));
  MSG_DM_CLIENT_DOMAIN_CREATE_ACK_descriptor_ = file->message_type(1);
  static const int MSG_DM_CLIENT_DOMAIN_CREATE_ACK_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DM_CLIENT_DOMAIN_CREATE_ACK, statuscode_),
  };
  MSG_DM_CLIENT_DOMAIN_CREATE_ACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MSG_DM_CLIENT_DOMAIN_CREATE_ACK_descriptor_,
      MSG_DM_CLIENT_DOMAIN_CREATE_ACK::default_instance_,
      MSG_DM_CLIENT_DOMAIN_CREATE_ACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DM_CLIENT_DOMAIN_CREATE_ACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_DM_CLIENT_DOMAIN_CREATE_ACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MSG_DM_CLIENT_DOMAIN_CREATE_ACK));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_CLIENT_DM_DOMAIN_CREATE_descriptor_, &MSG_CLIENT_DM_DOMAIN_CREATE::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MSG_DM_CLIENT_DOMAIN_CREATE_ACK_descriptor_, &MSG_DM_CLIENT_DOMAIN_CREATE_ACK::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto() {
  delete MSG_CLIENT_DM_DOMAIN_CREATE::default_instance_;
  delete MSG_CLIENT_DM_DOMAIN_CREATE_reflection_;
  delete MSG_DM_CLIENT_DOMAIN_CREATE_ACK::default_instance_;
  delete MSG_DM_CLIENT_DOMAIN_CREATE_ACK_reflection_;
}

void protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!MSG_CLIENT_DM_DOMAIN_CREATE.proto\"\217\001\n\033"
    "MSG_CLIENT_DM_DOMAIN_CREATE\022\r\n\005token\030\001 \001"
    "(\t\022\022\n\ndomainName\030\002 \001(\t\022\031\n\021domainDescript"
    "ion\030\003 \001(\t\022\017\n\007coreNum\030\004 \001(\r\022\017\n\007memSize\030\005 "
    "\001(\r\022\020\n\010filePath\030\006 \003(\t\"5\n\037MSG_DM_CLIENT_D"
    "OMAIN_CREATE_ACK\022\022\n\nstatusCode\030\001 \001(\005", 236);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MSG_CLIENT_DM_DOMAIN_CREATE.proto", &protobuf_RegisterTypes);
  MSG_CLIENT_DM_DOMAIN_CREATE::default_instance_ = new MSG_CLIENT_DM_DOMAIN_CREATE();
  MSG_DM_CLIENT_DOMAIN_CREATE_ACK::default_instance_ = new MSG_DM_CLIENT_DOMAIN_CREATE_ACK();
  MSG_CLIENT_DM_DOMAIN_CREATE::default_instance_->InitAsDefaultInstance();
  MSG_DM_CLIENT_DOMAIN_CREATE_ACK::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto {
  StaticDescriptorInitializer_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto() {
    protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto();
  }
} static_descriptor_initializer_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int MSG_CLIENT_DM_DOMAIN_CREATE::kTokenFieldNumber;
const int MSG_CLIENT_DM_DOMAIN_CREATE::kDomainNameFieldNumber;
const int MSG_CLIENT_DM_DOMAIN_CREATE::kDomainDescriptionFieldNumber;
const int MSG_CLIENT_DM_DOMAIN_CREATE::kCoreNumFieldNumber;
const int MSG_CLIENT_DM_DOMAIN_CREATE::kMemSizeFieldNumber;
const int MSG_CLIENT_DM_DOMAIN_CREATE::kFilePathFieldNumber;
#endif  // !_MSC_VER

MSG_CLIENT_DM_DOMAIN_CREATE::MSG_CLIENT_DM_DOMAIN_CREATE()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_CLIENT_DM_DOMAIN_CREATE::InitAsDefaultInstance() {
}

MSG_CLIENT_DM_DOMAIN_CREATE::MSG_CLIENT_DM_DOMAIN_CREATE(const MSG_CLIENT_DM_DOMAIN_CREATE& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_CLIENT_DM_DOMAIN_CREATE::SharedCtor() {
  _cached_size_ = 0;
  token_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  domainname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  domaindescription_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  corenum_ = 0u;
  memsize_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_CLIENT_DM_DOMAIN_CREATE::~MSG_CLIENT_DM_DOMAIN_CREATE() {
  SharedDtor();
}

void MSG_CLIENT_DM_DOMAIN_CREATE::SharedDtor() {
  if (token_ != &::google::protobuf::internal::kEmptyString) {
    delete token_;
  }
  if (domainname_ != &::google::protobuf::internal::kEmptyString) {
    delete domainname_;
  }
  if (domaindescription_ != &::google::protobuf::internal::kEmptyString) {
    delete domaindescription_;
  }
  if (this != default_instance_) {
  }
}

void MSG_CLIENT_DM_DOMAIN_CREATE::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_CLIENT_DM_DOMAIN_CREATE::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_CLIENT_DM_DOMAIN_CREATE_descriptor_;
}

const MSG_CLIENT_DM_DOMAIN_CREATE& MSG_CLIENT_DM_DOMAIN_CREATE::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto();  return *default_instance_;
}

MSG_CLIENT_DM_DOMAIN_CREATE* MSG_CLIENT_DM_DOMAIN_CREATE::default_instance_ = NULL;

MSG_CLIENT_DM_DOMAIN_CREATE* MSG_CLIENT_DM_DOMAIN_CREATE::New() const {
  return new MSG_CLIENT_DM_DOMAIN_CREATE;
}

void MSG_CLIENT_DM_DOMAIN_CREATE::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_token()) {
      if (token_ != &::google::protobuf::internal::kEmptyString) {
        token_->clear();
      }
    }
    if (has_domainname()) {
      if (domainname_ != &::google::protobuf::internal::kEmptyString) {
        domainname_->clear();
      }
    }
    if (has_domaindescription()) {
      if (domaindescription_ != &::google::protobuf::internal::kEmptyString) {
        domaindescription_->clear();
      }
    }
    corenum_ = 0u;
    memsize_ = 0u;
  }
  filepath_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_CLIENT_DM_DOMAIN_CREATE::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string token = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->token().data(), this->token().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_domainName;
        break;
      }
      
      // optional string domainName = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_domainName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_domainname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->domainname().data(), this->domainname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_domainDescription;
        break;
      }
      
      // optional string domainDescription = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_domainDescription:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_domaindescription()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->domaindescription().data(), this->domaindescription().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_coreNum;
        break;
      }
      
      // optional uint32 coreNum = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_coreNum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &corenum_)));
          set_has_corenum();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_memSize;
        break;
      }
      
      // optional uint32 memSize = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_memSize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &memsize_)));
          set_has_memsize();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_filePath;
        break;
      }
      
      // repeated string filePath = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_filePath:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_filepath()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->filepath(0).data(), this->filepath(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_filePath;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_CLIENT_DM_DOMAIN_CREATE::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string token = 1;
  if (has_token()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->token(), output);
  }
  
  // optional string domainName = 2;
  if (has_domainname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->domainname().data(), this->domainname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->domainname(), output);
  }
  
  // optional string domainDescription = 3;
  if (has_domaindescription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->domaindescription().data(), this->domaindescription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->domaindescription(), output);
  }
  
  // optional uint32 coreNum = 4;
  if (has_corenum()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->corenum(), output);
  }
  
  // optional uint32 memSize = 5;
  if (has_memsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->memsize(), output);
  }
  
  // repeated string filePath = 6;
  for (int i = 0; i < this->filepath_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->filepath(i).data(), this->filepath(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->filepath(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_CLIENT_DM_DOMAIN_CREATE::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string token = 1;
  if (has_token()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->token(), target);
  }
  
  // optional string domainName = 2;
  if (has_domainname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->domainname().data(), this->domainname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->domainname(), target);
  }
  
  // optional string domainDescription = 3;
  if (has_domaindescription()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->domaindescription().data(), this->domaindescription().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->domaindescription(), target);
  }
  
  // optional uint32 coreNum = 4;
  if (has_corenum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->corenum(), target);
  }
  
  // optional uint32 memSize = 5;
  if (has_memsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->memsize(), target);
  }
  
  // repeated string filePath = 6;
  for (int i = 0; i < this->filepath_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->filepath(i).data(), this->filepath(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(6, this->filepath(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_CLIENT_DM_DOMAIN_CREATE::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string token = 1;
    if (has_token()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->token());
    }
    
    // optional string domainName = 2;
    if (has_domainname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->domainname());
    }
    
    // optional string domainDescription = 3;
    if (has_domaindescription()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->domaindescription());
    }
    
    // optional uint32 coreNum = 4;
    if (has_corenum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->corenum());
    }
    
    // optional uint32 memSize = 5;
    if (has_memsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->memsize());
    }
    
  }
  // repeated string filePath = 6;
  total_size += 1 * this->filepath_size();
  for (int i = 0; i < this->filepath_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->filepath(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_CLIENT_DM_DOMAIN_CREATE::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_CLIENT_DM_DOMAIN_CREATE* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_CLIENT_DM_DOMAIN_CREATE*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_CLIENT_DM_DOMAIN_CREATE::MergeFrom(const MSG_CLIENT_DM_DOMAIN_CREATE& from) {
  GOOGLE_CHECK_NE(&from, this);
  filepath_.MergeFrom(from.filepath_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_token()) {
      set_token(from.token());
    }
    if (from.has_domainname()) {
      set_domainname(from.domainname());
    }
    if (from.has_domaindescription()) {
      set_domaindescription(from.domaindescription());
    }
    if (from.has_corenum()) {
      set_corenum(from.corenum());
    }
    if (from.has_memsize()) {
      set_memsize(from.memsize());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_CLIENT_DM_DOMAIN_CREATE::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_CLIENT_DM_DOMAIN_CREATE::CopyFrom(const MSG_CLIENT_DM_DOMAIN_CREATE& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_CLIENT_DM_DOMAIN_CREATE::IsInitialized() const {
  
  return true;
}

void MSG_CLIENT_DM_DOMAIN_CREATE::Swap(MSG_CLIENT_DM_DOMAIN_CREATE* other) {
  if (other != this) {
    std::swap(token_, other->token_);
    std::swap(domainname_, other->domainname_);
    std::swap(domaindescription_, other->domaindescription_);
    std::swap(corenum_, other->corenum_);
    std::swap(memsize_, other->memsize_);
    filepath_.Swap(&other->filepath_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_CLIENT_DM_DOMAIN_CREATE::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_CLIENT_DM_DOMAIN_CREATE_descriptor_;
  metadata.reflection = MSG_CLIENT_DM_DOMAIN_CREATE_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MSG_DM_CLIENT_DOMAIN_CREATE_ACK::kStatusCodeFieldNumber;
#endif  // !_MSC_VER

MSG_DM_CLIENT_DOMAIN_CREATE_ACK::MSG_DM_CLIENT_DOMAIN_CREATE_ACK()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::InitAsDefaultInstance() {
}

MSG_DM_CLIENT_DOMAIN_CREATE_ACK::MSG_DM_CLIENT_DOMAIN_CREATE_ACK(const MSG_DM_CLIENT_DOMAIN_CREATE_ACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::SharedCtor() {
  _cached_size_ = 0;
  statuscode_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MSG_DM_CLIENT_DOMAIN_CREATE_ACK::~MSG_DM_CLIENT_DOMAIN_CREATE_ACK() {
  SharedDtor();
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_DM_CLIENT_DOMAIN_CREATE_ACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_DM_CLIENT_DOMAIN_CREATE_ACK_descriptor_;
}

const MSG_DM_CLIENT_DOMAIN_CREATE_ACK& MSG_DM_CLIENT_DOMAIN_CREATE_ACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MSG_5fCLIENT_5fDM_5fDOMAIN_5fCREATE_2eproto();  return *default_instance_;
}

MSG_DM_CLIENT_DOMAIN_CREATE_ACK* MSG_DM_CLIENT_DOMAIN_CREATE_ACK::default_instance_ = NULL;

MSG_DM_CLIENT_DOMAIN_CREATE_ACK* MSG_DM_CLIENT_DOMAIN_CREATE_ACK::New() const {
  return new MSG_DM_CLIENT_DOMAIN_CREATE_ACK;
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    statuscode_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MSG_DM_CLIENT_DOMAIN_CREATE_ACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 statusCode = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &statuscode_)));
          set_has_statuscode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 statusCode = 1;
  if (has_statuscode()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->statuscode(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MSG_DM_CLIENT_DOMAIN_CREATE_ACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 statusCode = 1;
  if (has_statuscode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->statuscode(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MSG_DM_CLIENT_DOMAIN_CREATE_ACK::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 statusCode = 1;
    if (has_statuscode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->statuscode());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MSG_DM_CLIENT_DOMAIN_CREATE_ACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MSG_DM_CLIENT_DOMAIN_CREATE_ACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::MergeFrom(const MSG_DM_CLIENT_DOMAIN_CREATE_ACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_statuscode()) {
      set_statuscode(from.statuscode());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::CopyFrom(const MSG_DM_CLIENT_DOMAIN_CREATE_ACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_DM_CLIENT_DOMAIN_CREATE_ACK::IsInitialized() const {
  
  return true;
}

void MSG_DM_CLIENT_DOMAIN_CREATE_ACK::Swap(MSG_DM_CLIENT_DOMAIN_CREATE_ACK* other) {
  if (other != this) {
    std::swap(statuscode_, other->statuscode_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MSG_DM_CLIENT_DOMAIN_CREATE_ACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_DM_CLIENT_DOMAIN_CREATE_ACK_descriptor_;
  metadata.reflection = MSG_DM_CLIENT_DOMAIN_CREATE_ACK_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
